deployments:
  deploymentGating:
    enabled: true # to enable the feature
    retry: 50 # run poll action 50 times
    sleep: 30 # wait 30 seconds between each poll
    environments: # select the environments you'd like to use with this feature
    - Production
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2U5MGU4ODRhLTk1ODEtNDI2Yy1hMTZkLTVmNmNmMzIyN2VkYi9kZTNlM2QyNC1mOGQzLTExZWYtOGUxMy0wYWZmZjNkZDM0Nzc=
